[package]
name = "test_fast_api_module"
version = "0.1.0"
edition = "2021"


[lib]
name = "rust_module"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.15", features = ["extension-module"] }
